theme: jekyll-theme-midnight
title: Welcome to Jeremy's webpage!
description: I'll do my best to use this webpage to update this page with anything of note that I have accomplished. Kind of like a resume!
